version: "3"
services:
  postgres:
    image: postgres:15.2-alpine
    networks:
      - postgres
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - postgres
    networks:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

networks:
  postgres:
    driver: bridge